### ISSUE TITLE
Dependency "time 0.3.31" fails to compile using Rust >=1.80.0

### ISSUE THREAD

**Issue by ShamrockLee** [sidju/hired#45]
The Cargo.lock specifies that hired currently depends on `time 0.3.31`, which fails to compile with rustc 1.84.0.

The following error appears when trying to package hired for [Nixpkgs](https://github.com/NixOS/nixpkgs).

```
hired>    Compiling time v0.3.31
hired> error[E0282]: type annotations needed for `Box<_>`
hired>   --> /build/hired-0.12.0-vendor.tar.gz/time/src/format_description/parse/mod.rs:83:9
hired>    |
hired> 83 |     let items = format_items
hired>    |         ^^^^^
hired> ...
hired> 86 |     Ok(items.into())
hired>    |              ---- type must be known at this point
hired>    |
hired>    = note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update`
hired> For more information about this error, try `rustc --explain E0282`.
```

The current stable Rust version is 1.83.0, and 1.84.0 will become stable two days later. Maybe we should update the `time` dependency to  make hired compile on the stable Rust release.

**Comment by sidju** [comment]
Thank you for the report, I haven't made a new install in a while. I'll get it sorted some time tomorrow (and maybe squash some other issue as well).

-------- Original Message --------

**Comment by sidju** [comment]
Should be solved in 0.12.1
